# Cloud Build configuration for Google Cloud Run deployment
substitutions:
  _IMAGE_TAG: '${SHORT_SHA}'  # Will use BUILD_ID if SHORT_SHA is empty

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gorgias-mcp-server:${_IMAGE_TAG}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gorgias-mcp-server:latest'
      - '-f'
      - 'Dockerfile.cloudrun'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/gorgias-mcp-server:${_IMAGE_TAG}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/gorgias-mcp-server:latest'

  # Deploy container image to Cloud Run
  # Note: Credentials (GORGIAS_API_KEY, GORGIAS_USERNAME) are NOT set here
  # They must be configured separately via: gcloud run services update --set-env-vars
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gorgias-mcp-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gorgias-mcp-server:${_IMAGE_TAG}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--port'
      - '8080'
      - '--update-env-vars'
      - 'GORGIAS_BASE_URL=https://petstoredirect.gorgias.com/api/,DEBUG=false'

images:
  - 'gcr.io/$PROJECT_ID/gorgias-mcp-server:${_IMAGE_TAG}'
  - 'gcr.io/$PROJECT_ID/gorgias-mcp-server:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

