# Cloud Build configuration for Google Cloud Run deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gorgias-mcp-server:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gorgias-mcp-server:latest'
      - '-f'
      - 'Dockerfile.cloudrun'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/gorgias-mcp-server:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/gorgias-mcp-server:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gorgias-mcp-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gorgias-mcp-server:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '60'
      - '--port'
      - '8080'

images:
  - 'gcr.io/$PROJECT_ID/gorgias-mcp-server:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/gorgias-mcp-server:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

