#!/usr/bin/env python3
"""Setup script for Gorgias MCP Server.

This script helps you configure the Gorgias MCP Server by prompting for
the required credentials and creating a .env file.
"""

import os
import sys
from pathlib import Path


def get_input(prompt, default=None, required=True):
    """Get user input with optional default value."""
    while True:
        if default:
            full_prompt = f"{prompt} [{default}]: "
        else:
            full_prompt = f"{prompt}: "
        
        value = input(full_prompt).strip()
        
        if value:
            return value
        elif default:
            return default
        elif not required:
            return ""
        else:
            print("This field is required. Please enter a value.")


def validate_credentials(api_key, base_url, username):
    """Validate the provided credentials."""
    print("\n🔍 Validating credentials...")
    
    # Basic validation
    if not api_key or len(api_key) < 10:
        print("❌ API key appears to be invalid (too short)")
        return False
    
    if not username or "@" not in username:
        print("❌ Username should be a valid email address")
        return False
    
    if not base_url or not base_url.startswith("https://"):
        print("❌ Base URL should start with https://")
        return False
    
    print("✅ Credentials appear to be valid")
    return True


def create_env_file(api_key, base_url, username):
    """Create .env file with the provided credentials."""
    env_content = f"""# Gorgias MCP Server Configuration
# Generated by setup.py

# Required: Your Gorgias API key
GORGIAS_API_KEY={api_key}

# Required: Your Gorgias username/email
GORGIAS_USERNAME={username}

# Required: Your Gorgias API base URL
GORGIAS_BASE_URL={base_url}

# Optional: Enable debug logging (true/false)
DEBUG=false
"""
    
    env_path = Path(".env")
    try:
        with open(env_path, "w") as f:
            f.write(env_content)
        print(f"✅ Created .env file at {env_path.absolute()}")
        return True
    except Exception as e:
        print(f"❌ Failed to create .env file: {e}")
        return False


def test_connection(api_key, base_url, username):
    """Test the API connection with the provided credentials."""
    print("\n🧪 Testing API connection...")
    
    try:
        # Set environment variables for testing
        os.environ["GORGIAS_API_KEY"] = api_key
        os.environ["GORGIAS_BASE_URL"] = base_url
        os.environ["GORGIAS_USERNAME"] = username
        
        # Import and test
        sys.path.append(".")
        from src.utils.auth import GorgiasAuth
        from src.utils.api_client import GorgiasAPIClient
        import asyncio
        
        async def test():
            auth = GorgiasAuth()
            client = GorgiasAPIClient(auth)
            response = await client.get("customers", params={"limit": 1})

            if isinstance(response, dict):
                if response.get("data") is not None:
                    return True
                if response.get("status_code") == 204:
                    return True

            return bool(response)
        
        result = asyncio.run(test())
        if result:
            print("✅ API connection successful!")
            return True
        else:
            print("❌ API connection failed")
            return False
            
    except Exception as e:
        print(f"❌ API connection test failed: {e}")
        return False


def main():
    """Main setup function."""
    print("🚀 Gorgias MCP Server Setup")
    print("=" * 40)
    print()
    print("This script will help you configure the Gorgias MCP Server.")
    print("You'll need your Gorgias API credentials ready.")
    print()
    
    # Check if .env already exists
    if Path(".env").exists():
        overwrite = input("⚠️  .env file already exists. Overwrite? [y/N]: ").strip().lower()
        if overwrite not in ['y', 'yes']:
            print("Setup cancelled.")
            return
    
    print("\n📋 Please provide your Gorgias credentials:")
    print()
    
    # Get credentials
    api_key = get_input(
        "Gorgias API Key",
        required=True
    )
    
    username = get_input(
        "Gorgias Username (email)",
        required=True
    )
    
    base_url = get_input(
        "Gorgias Base URL",
        default="https://petstoredirect.gorgias.com/api/",
        required=True
    )
    
    # Validate credentials
    if not validate_credentials(api_key, base_url, username):
        print("\n❌ Setup failed due to invalid credentials.")
        return
    
    # Test connection
    if not test_connection(api_key, base_url, username):
        print("\n❌ Setup failed due to connection issues.")
        print("Please check your credentials and try again.")
        return
    
    # Create .env file
    if not create_env_file(api_key, base_url, username):
        print("\n❌ Setup failed to create configuration file.")
        return
    
    print("\n🎉 Setup completed successfully!")
    print()
    print("Next steps:")
    print("1. Run the MCP server: python -m src.server")
    print("2. Or test with MCP Inspector: mcp-inspector")
    print()
    print("Your credentials are saved in .env file.")
    print("Keep this file secure and don't commit it to version control.")


if __name__ == "__main__":
    main()
